### ISSUE TITLE
Sugestion: rename the package to language-dircolors

### ISSUE THREAD

**Issue by varemenos** [jolkdarr/language-dircolors#1]
This is actually a package that contains the grammar for dircolors so it should follow the convention that all grammar-related packages use which is to preppend the `language-` to the package name.

examples at: https://github.com/atom?utf8=%E2%9C%93&query=language-

(great package btw)

**Comment by jolkdarr** [comment]
Renamed through:

``` sh
apm publish major --rename language-dircolors
```

Thanks for the reporting.

**Comment by varemenos** [comment]
Great, thank you :)
